### ISSUE TITLE
Return Promises

### ISSUE THREAD

**Issue by sohunn** [DevelopmentCubed/eris-interaction-listener#1]
Instead of explicitly handling promises while acknowledging an interaction (lib wise), wouldn't it be better if that settled promise was returned?

In short, what I mean is, the `request()` method of Eris's RequestHandler returns a promise and that can be returned back. This makes it more flexible for the end user to perform whatever they need to do based on the state of that Promise, instead of the lib just logging it to the console. 

I can submit a pull request for the change but I wanted to discuss it first before doing so.

**Comment by Azorant** [comment]
Yea that's a good idea.

**Comment by FireGamer3** [comment]
If you would like to you can submit a PR to fix this.
